nome = input(" digite seu nome:")
print ("Bem vindo senhor  " + nome + " novamente")
dia = input( "dia do seu nascimento:")
mes = input ("mes do seu nascimento:")
ano = input ("ano do seu nascimento:")
print ("você nasxeu em " + dia + "/" + mes + "/" + ano)
